#!/bin/sh
set -e

echo "Running pre-commit checks on staged files..."

STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$' || true)

if [ -z "$STAGED_GO_FILES" ]; then
  echo "No Go files staged for commit."
  exit 0
fi

echo "$STAGED_GO_FILES" | xargs -r gofmt -s -w
echo "$STAGED_GO_FILES" | xargs -r git add

echo "$STAGED_GO_FILES" | xargs -r -I {} dirname {} | sort -u | xargs -r ./bin/golangci-lint run --fix

go test ./...

echo "Pre-commit checks passed on staged files!"
